-<?php
-$currency = '$'; //Currency sumbol or code
-
-$db_username = 'dle232';
-$db_password = 'u0816536';
-$db_name = 'test';
-$db_host = 'mastelottoplan.backups.uky.edu';
-$mysqli = new mysqli($db_host, $db_username, $db_password,$db_name);
-?>